server:
  port: 8081

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/orclpdb
    username: blog
    password: blog
  jpa:
    hibernate:
      ddl-auto: update
    security:
      enabled: false

security:
  basic:
    enabled: false

management:
  security:
    enabled: false