server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_trace_param
    include-exception: true

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/orclpdb
    username: blog
    password: blog
  jpa:
    hibernate:
      ddl-auto: update
    security:
      enabled: false

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

jwt:
  secret: 123456