server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_trace_param
    include-exception: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    security:
      enabled: false

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

jwt:
  secret: 123456
